[package]
name = "zk_lib_cairo"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.20.0" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"